### ISSUE TITLE
Does not work with musl compiler (Alpine node docker image)

### ISSUE THREAD

**Issue by gabormagyar** [mscdex/buildcheck#3]
The error:

```
/builder/.yarn/unplugged/buildcheck-npm-0.0.3-ac31c4ae43/node_modules/buildcheck/lib/index.js:117
  throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at BuildEnvironment.getKind (/builder/.yarn/unplugged/buildcheck-npm-0.0.3-ac31c4ae43/node_modules/buildcheck/lib/index.js:117:9)
    at BuildEnvironment.tryCompile (/builder/.yarn/unplugged/buildcheck-npm-0.0.3-ac31c4ae43/node_modules/buildcheck/lib/index.js:539:15)
    at BuildEnvironment.checkHeader (/builder/.yarn/unplugged/buildcheck-npm-0.0.3-ac31c4ae43/node_modules/buildcheck/lib/index.js:425:25)
    at Object.<anonymous> (/builder/.yarn/unplugged/cpu-features-npm-0.0.4-b474ef5da3/node_modules/cpu-features/buildcheck.js:16:4)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (/builder/.pnp.cjs:23065:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (/builder/.pnp.cjs:22888:22)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
```

This happens because `const result = spawnSync(...` on line [:65](https://github.com/mscdex/buildcheck/blob/master/lib/index.js#L65) errors with the following:

```js
// value of result
{
  "error": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "spawnSync cc",
    "path": "cc",
    "spawnargs": ["-E", "-P", "-x", "c", "-"]
  },
  "status": null,
  "signal": null,
  "output": null,
  "pid": 86,
  "stdout": null,
  "stderr": null
}
```

Subsequent error from caller lib, for searchability:
```
Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided
```

Dockerfile to reproduce:
```
FROM node:16-alpine as builder
WORKDIR /builder

COPY . .

RUN yarn install || (cat /tmp/*/build.log; exit 13;)
```

This is on an M1 mac

**Comment by kevinolivar** [comment]
Any news about that issue?

**Comment by mscdex** [comment]
ENOENT when attempting to spawn `cc` means it couldn't find the compiler at all, so it has nothing to do with the libc. I'm not sure why that would be happening though, since it's supposed to [create the `cc` symlink when installing the `gcc` package](https://git.alpinelinux.org/aports/tree/main/gcc/APKBUILD?h=3.16-stable#n376).

**Comment by mscdex** [comment]
Actually, after re-reading the node Dockerfile, it appears gcc/g++ isn't installed if node isn't built from source, so you may have to explicitly install a compiler first to ensure one gets included.
